Шаблонизируй то
htmlacademy-ecmascript/2323243-big-trip-20 pull request #6
Opened 2023-06-03 08:42 UTC by GermanBurdin1

…Refactor markup & form closure.

2023-06-04 05:16 UTC, IngSm requested changes

2023-06-04 05:16 UTC, IngSm commented on src/presenter/board-presenter.js
> +      onResetClick: () => {
Одинаковый функционал внутри свойств: зачем?

2023-06-04 05:16 UTC, IngSm commented on src/presenter/filter-presenter.js
> +    this.#filters = generateFilters(this.#pointsModel.points);
`#pointsModel` - нужен только для использования в консрукторе для генерации фильтров? Если да, то лишняя переменная

2023-06-05 13:56 UTC, GermanBurdin1 commented on src/presenter/board-presenter.js
> +      onResetClick: () => {
Сейчас при нажатии на save и кнопку сброса форма закрывается,
но в дальнейшем логика разделится. При сбросе (reset) карточка также сбросится, при save, данные сохранятся и уйдут на сервер (наверно)

2023-06-07 04:15 UTC, merged